export const VEHICLE_FETCHED = "VEHICLE_FETCHED";
export const VEHICLE_USERS_FETCHED = "VEHICLE_USERS_FETCHED";
export const VEHICLE_USER_REMOVED = "VEHICLE_USER_REMOVED";
export const VEHICLE_USER_ADDED = "VEHICLE_USER_ADDED";
export const ROLES_FETCHED = "ROLES_FETCHED";
